# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  peer0.dummyOrg.com:
    container_name: peer0.dummyOrg.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dummyOrg.com
      - CORE_PEER_ADDRESS=peer0.dummyOrg.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dummyOrg.com:7051
      - CORE_PEER_LOCALMSPID=dummyOrgMSP
      
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dummyOrg.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dummyOrg.com/peers/peer0.dummyOrg.com/msp:/etc/hyperledger/fabric/msp
    ports:
      - 7051:7051
