# Copyright [2020] [Frantz Darbon, Gilles Seghaier, Johan Tombre, Frédéric Vaz]

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ==============================================================================

version: '2'

services:
  ca.root.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.root.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_LOGGING_SPEC=debug
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start  -b adminCA:adminpw -d'
    container_name: ca.root.example.com
    volumes:  
     - ./scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/

  ca.org1.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_LOGGING_SPEC=debug
      - IP_ROOT=${IP_ROOT}
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start  -b admin:adminpw -d -u http://ca.org1.example.com:adminpw@${IP_ROOT}:7054'
    volumes:  
     - ./crypto-config/ica-servers/certsICAOrg1:/etc/hyperledger/fabric-ca-server
     - ./crypto-config/ica-servers/certsICAOrg1:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.example.com

  ca.org2.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server-config
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_LOGGING_SPEC=debug
      - IP_ROOT=${IP_ROOT}
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start  -b admin:adminpw -d -u http://ca.org2.example.com:adminpw@${IP_ROOT}:7054'
    volumes:  
     - ./crypto-config/ica-servers/certsICAOrg2:/etc/hyperledger/fabric-ca-server
     - ./crypto-config/ica-servers/certsICAOrg2:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.example.com

###############################################################
############################ CLI ##############################
############################################################### 
  ca-cli:
    container_name: ca-cli
    image: hyperledger/fabric-ca
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
     # - CORE_LOGGING_LEVEL=DEBUG
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/MyCertificate.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/MyKey.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/ca/ca.org1.example.com.crt.pem
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      - IP_ROOT=${IP_ROOT}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/filechain
    volumes:
        - ./:/opt/gopath/src/github.com/hyperledger/fabric/filechain
    depends_on:
      - ca.root.example.com
